const AUTO_COMMENT = '# THIS IS AN AUTOGENERATED FILE\n\n';

/**
 * @param {Array} plugins
 * @returns {Array}
 */
function flattenRules(plugins) {
  return plugins.reduce((collection, plugin) => {
    const { rules } = plugin;

    return collection.concat(rules);
  }, []);
}

/**
 * @param {Array} rules
 * @returns {String}
 */
function stringifyRules(rules) {
  return rules.reduce((collection, rules) => {
    const { path, docsURL } = rules;

    return collection.concat(`/${path}  ${docsURL}  302\n`)
  }, '');
}

/**
 * @param {Array} plugins
 * @returns {Promise} A promise to return a string
 */
async function createRedirects(plugins) {
  const rules = flattenRules(plugins);
  const stringifiedRules = stringifyRules(rules);

  return `${AUTO_COMMENT}${stringifiedRules}`;
}

module.exports = createRedirects;
