const AUTO_COMMENT = '# THIS IS AN AUTOGENERATED FILE\n\n';

/**
 * Transform all rules into a string
 *
 * @param {Array} rules
 * @returns {Promise} A promised string of rules
 */
async function stringifyRules(rules) {
  return rules.reduce((collection, rules) => {
    const { path, docsURL } = rules;

    return collection.concat(`/${path}  ${docsURL}  302\n`)
  }, AUTO_COMMENT);
}

module.exports = stringifyRules;
